spring.application.name=interview2

spring.datasource.url=jdbc:mysql://localhost:3306/product_management
spring.datasource.username=root
spring.datasource.password=postgres123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=hm14yYmRyyJNBEL0ypIEI44PBVcAXpynJCqsi1izUQu
app.jwt.expiration=86400000
